task3 upload
yumi0109/kintone_dojo pull request #3
Opened 2023-06-19 02:39 UTC by yumi0109

お疲れさまです。
Dojoの課題『JavaScript課題②』の提出です。
お時間ある際に、ご確認よろしくお願いします。

2023-06-22 02:23 UTC, poemypoemy8 commented on task3/task3.html
> +    if (fileManage[key][val] === 'Everyone'){
手順3-2/3-3のインデントがずれていると思います！
https://rybb.github.io/dojo-jswatchdog/
にコードを入れて確認をお願いします。

2023-06-22 02:23 UTC, poemypoemy8 commented on task3/task3.html
> +    if (fileManage[key][val] === 'Everyone'){
`if (fileManage[key][val] === 'Everyone'){`
を 
`Object.keys(fileManage[key]).forEach((val) =>{`
の外に出して実装する方法もありそうです。
（ifに対して、(val)のループかける必要なさそうです）

今回は「閲覧権限がEveryoneなら」なので、
そのあたりも含めて修正できないか考えてみてください！

もし難しそうならまたコメントくださいm(_ _)m

2023-06-22 02:23 UTC, poemypoemy8 commented on task3/task3.html
> +  console.log(fileManage);
デバッグ残っているので削除しておいてください！

2023-06-22 02:27 UTC, poemypoemy8 commented
@yumi0109 
遅くなりました（ごめんなさい！＞＜）
課題おつかれさまでした🎉

他の課題もある中で修正事項なので大変とは思いますが、
色々と試行錯誤しながら取り組んでみてくださいね。

詰まりすぎてしんどい！となったらいつでも声かけてください。
ヒント出させていただきます🤹‍♂️

2023-06-25 23:32 UTC, poemypoemy8 commented
@yumi0109 
課題おつかれさまです！修正点は問題なさそうでしょうか？
その他の課題も進めてくれているためだと思いますが、もしわからなければ遠慮なくコメントくださいね！
（ヒント出します）

2023-06-26 00:00 UTC, poemypoemy8 requested changes
修正依頼届いてなかったですかね？(;'∀')

2023-06-26 00:52 UTC, poemypoemy8 commented
@yumi0109 
あえてお伝えしていなかったので申し訳ないのですが、
ゆーみんのレビューはわたしが担当する予定なので
レビュアーはわたしのみに変更お願いしますm(_ _)m

2023-06-26 01:14 UTC, yumi0109 commented
@poemypoemy8 
レビューありがとうございます。
レビュー届いています！返信と修正できておらずすみません。

午前中考えて、難しければ、今日の午後のミーティングで質問させていただきますので、よろしくお願いいたします。

2023-06-26 06:20 UTC, yumi0109 commented
task3を修正して、『task3 version2』としてアップロードさせていただきました。

ifに対して、(val)のループかける必要なさそうとのアドバイスをもとに、ifを
『Object.keys(fileManage[key]).forEach((val) => { .........}』の外に出して、閲覧権限がEveryoneの場合のみの記述を下に書きました。(『if (fileManage[key].viewAuth === 'Everyone'』の部分が該当しています。)

お手隙の際にご確認よろしくお願いします。

2023-06-26 08:17 UTC, poemypoemy8 requested changes
@

2023-06-26 08:17 UTC, poemypoemy8 commented on task3/task3.html
>    Object.keys(fileManage[key]).forEach((val) =>{
＞ifに対して、(val)のループかける必要なさそうとのアドバイスをもとに、ifを
『Object.keys(fileManage[key]).forEach((val) => { .........}』の外に出して、閲覧権限がEveryoneの場合のみの記述を下に書きました。(『if (fileManage[key].viewAuth === 'Everyone'』の部分が該当しています。)

修正おつかれさまでした！
コメントで書いてくれていた通りの認識でOKそうです！
ただ、自分が今見ているプルリクエストだと反映されていないように見えます…(・・;)

上記コメントの通りすでに理解されていると思うので、
コードに反映されているかどうかだけ再度確認お願いします！

2023-07-06 12:50 UTC, poemypoemy8 commented
@yumi0109 
こちら問題なさそうですか(;´･ω･)？
何か詰まってたらおしえてくださいね！

2023-07-07 00:32 UTC, merged