task4 upload
yumi0109/kintone_dojo pull request #4
Opened 2023-06-20 02:23 UTC by yumi0109

お疲れさまです。
「JavaScript課題③」の課題で「task4-1.html」 と「task4-2.html」を提出しています。
お時間ある際に、ご確認よろしくお願いします。

2023-06-22 02:23 UTC, poemypoemy8 commented on task4/task4-1.html
> +    document.getElementById('price').textContent = basePrice + Number(totalOptionPrice);
`document.getElementById('price').textContent = basePrice + Number(totalOptionPrice);`

右辺を変数ひとつにしてまとめる方法がないでしょうか…！

2023-06-22 02:23 UTC, poemypoemy8 commented on task4/task4-2.html
> +    document.getElementById('price').textContent = basePrice + Number(secureOptionPrice) + Number(addedDiscPrice);
ここも 4-1と同じです。
右辺を変数一つにしてまとめる方法がないか、考えてみてください＞＜

右辺を変数て一つにする場合、
`    let secureOptionPrice = 0;
    let addedDiscPrice = 0;
    const basePrice = 3900;`

このあたりの数値と、定義の場所を考える必要がありそうです！

2023-06-22 02:23 UTC, poemypoemy8 commented on task4/task4-2.html
> +    document.getElementById('price').textContent = basePrice + Number(secureOptionPrice) + Number(addedDiscPrice);
考えてどうにもなりそうになければコメントくださいね👀

2023-06-22 02:25 UTC, poemypoemy8 commented
@yumi0109 
おつかれさまです！課題おつかれさまでした🎅
（自分がgithubを理解してなく、レビューが登録できていなかったみたいで本当にごめんなさい）

基本的にはOKですが、上記レビューの通り
もう少しすっきりとさせたやり方がありそうなので、考えてみてくださいm(_ _)m
難しければ遠慮なく github上でもkintone上でもコメントくださいね！

2023-06-26 00:01 UTC, poemypoemy8 requested changes
こちらも修正依頼届いていなかったでしょうか？(;'∀')

2023-06-26 00:59 UTC, yumi0109 commented
レビューありがとうございます！
返信遅くなり、すみません。レビュー届いています。
task4 は4-1は解決できたと思うのですが、4-2の解決方法が見つけられていません。

terminal上で修正したとことを再度pushしようと思ったのですが、うまくいかないので、修正が上がるまでもう少し待っていただけると嬉しいです🙏🏻

2023-06-26 01:52 UTC, poemypoemy8 commented
@yumi0109 
承知しました！
まったくせかすつもりはないので焦らずでお願いします！
github系で困ったことがあれば定例で相談でも大丈夫なので！

2023-06-26 02:29 UTC, yumi0109 commented
@poemypoemy8 
ありがとうございます🙇‍♀️

task3と4の両方、課題自体の修正はできたので、定例でgithubの再度提出する方法についてお聞きしようと思います。
よろしくお願いします。

2023-06-26 05:57 UTC, yumi0109 commented
ミーティングでgithubでの提出方法教えていただきありがとうございました🙇‍♀️

task4-1のファイルがアップロードされていなかったので、『task4 version3』で再度上げさせていただきました。

◾️task4-1
『Baseprice=0』としていたものを『totalOptionPrice=3900』に定義して、『textContent』の『price』に表示する値からbasePriceを省きました。 

◾️task4-2
月額金額の最低料金の3900を『const』ではなく『let』で再代入できるように定義して、全体的にコードを変更しました。

お手隙の際にご確認よろしくお願いします。

2023-06-26 09:45 UTC, poemypoemy8 approved these changes
ばっちりです！修正お疲れさまでした🍵

意図していた、
4-1 `basePrice`を let で定義すること
4-2 ``btn`を押す際の初期値` basePrice `  に対しての演算
がばっちり反映されていたのでレビューOKです！

2023-06-26 09:46 UTC, poemypoemy8 commented
@yumi0109 
レビューOKなのでマージしてもらって構いません！
おつかれさまでした！

2023-06-28 07:58 UTC, merged