task8 upload
yumi0109/kintone_dojo pull request #5
Opened 2023-06-22 07:14 UTC by yumi0109

お疲れさまです！
順番がばらばらになっていますが、『kintone REST API課題①』の提出です。

お時間ある際にご確認よろしくお願いします。

(レビューしていただいた以前の課題は、回答できたらまたリクエストを送らせていただきます🙇‍♀️)

2023-06-26 02:04 UTC, poemypoemy8 requested changes

2023-06-26 02:04 UTC, poemypoemy8 commented on task8/task8.js
> +    'use strict';
インデントが全体的にずれていそうです。
jswatchdogにいれて修正をお願いします！

2023-06-26 02:10 UTC, poemypoemy8 commented
@yumi0109 
Task6 の修正後のほうがよさそうなので、
それまでレビュー待ちますね！m(_ _)m

2023-06-26 07:34 UTC, yumi0109 commented on task8/task8.js
> +    'use strict';
すみません、インデントのスペースを2ではなく、4の設定にしていました。
修正します！見にくいコードになってしまって、申し訳ありません...。

2023-06-28 01:59 UTC, poemypoemy8 requested changes
Task6の修正点を反映のうえで、
こちらにも適用お願いしますm(_ _)m

2023-06-28 03:00 UTC, poemypoemy8 requested changes
Promise ではなく async await で記述したんですね…！
基本的な処理は問題なさそうです！
ただTask6で指摘がのこっているじょがのこっているじょ

2023-06-28 03:00 UTC, poemypoemy8 commented on task8/task8.js
> +            app: 23
appId は、決め打ちの指定のほかに
以下リンクのようにコードで取得することもできます！
https://cybozu.dev/ja/kintone/docs/js-api/app/get-app-id/

2023-06-28 03:07 UTC, poemypoemy8 requested changes

2023-06-28 03:07 UTC, poemypoemy8 commented on task8/task8.js
> +        const options = resp.properties.Table.fields.Action5.options;
取得している構造が違うと思います。
respを見ながら正しい構造で記述しなおしてください！

2023-07-04 08:11 UTC, yumi0109 commented
@poemypoemy8 
task8を修正しましたので、お手隙の際にご確認よろしくお願いします。

2023-07-06 13:15 UTC, poemypoemy8 approved these changes
レビューOKです！ お疲れさまでした。
今回のコードでは、`subtableArry` に `.shift`メソッドを適用して、
`push` (追加)したものを `shift` (冒頭要素の取り出し)してテーブルに入れ込んでいるものと理解しました。

もし[Task6で書き直した記述](https://github.com/yumi0109/kintone_dojo/pull/6/files)を活かすなら、
arryRow という、作成した配列に 今回のrespで取得した `resp.properties.Table.fields.Action5.options`が適用されるように記述することもできそうかなと思いました。

今の記述のpush(追加)をして shift（取り出し）をするのは、なんだか無駄な処理に思えるので、
もし時間があってやり直しする際などには別の方法も考えてみてもらえるとうれしいです🙏

お疲れさまでした！

2023-07-07 01:31 UTC, merged

2023-07-07 01:34 UTC, yumi0109 commented
@poemypoemy8 
お疲れさまです。

レビューありがとうございます。

Task6で修正した方法をこちらにも適用せずに進めてしまい、すみません...。

製品研修の課題が終わったら、もう一度JavaScriptをやりたいなと思っているので、task8の別の方法も記述してみようと思います。

レビューとアドバイスありがとうございました。