task6 upload
yumi0109/kintone_dojo pull request #6
Opened 2023-06-22 07:27 UTC by yumi0109

お疲れさまです！

『JavaScript API課題』の1つ目の課題の提出になります。

お時間ある際にご確認よろしくお願いします。

2023-06-25 23:58 UTC, poemypoemy8 requested changes

2023-06-25 23:58 UTC, poemypoemy8 commented on task6/task6.js
> +    console.log(record);
デバッグ用のコードは
マージする前に削除してほしいので、
レビュー時には削除しておいてください🙆‍♀️

2023-06-25 23:58 UTC, poemypoemy8 commented on task6/task6.js
> +
オブジェクトの中身は記述できていると思います！👌

ただ、テーブルの記述方法が少し違っていそうです。
テーブルは、 配列の中にオブジェクトで中身を記述しています。
下記の記事を改めて見返して、テーブルの初期値の設定はどのようになるか検討のうえで修正をお願いします！
[kintoneにおけるテーブル操作の基本（行の追加・更新・削除）
](https://cybozudev.zendesk.com/hc/ja/articles/360022502911-kintone%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E6%93%8D%E4%BD%9C%E3%81%AE%E5%9F%BA%E6%9C%AC-%E8%A1%8C%E3%81%AE%E8%BF%BD%E5%8A%A0-%E6%9B%B4%E6%96%B0-%E5%89%8A%E9%99%A4-?_ga=2.111406404.1369754041.1687737010-868780843.1661920947)

2023-06-25 23:59 UTC, poemypoemy8 commented
@yumi0109 
課題お疲れさまでした！
レビューを登録したので、ご確認お願いします🙏

考えてわかりそうになければコメントくださいね！

2023-06-26 06:56 UTC, yumi0109 commented on task6/task6.js
> +
@poemypoemy8 
テーブルの初期値の設定について質問です。

初期値の設定で、『shifr()』を利用したのですが、他のコードで初期値を設定するということですか？
送っていだたいた記事を見たのですが、今回の課題でどの部分を適用すれば良いのか理解できずで...。

お忙しい中、お手数おかけして申し訳ないです🙏🏻

参照したURL：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/shift

2023-06-26 10:07 UTC, poemypoemy8 commented on task6/task6.js
> +
@yumi0109 
参照URLを見て理解しました。
記事で確認してほしかったのは、 「テーブルの構造」です。
`event.record.Table.value` は 、行が配列の形で定義されており、その中のvalueがオブジェクトの形になっています。

2023-06-26 10:21 UTC, poemypoemy8 commented on task6/task6.js
> +
回答のコードでは `.shift`メソッドを利用せず
`配列.push(オブジェクト)` の形で記述をしているのですが、
処理がうまくいっていれば回答のFBをしてOKにできればと考えています。

自分が「.shift」のメソッドを利用したことがなく、
`.shift ` のメソッドで、コードごとに意図している挙動をメモしてもらってもいいでしょうか？
（コメントアウトでメモしてコミット、もしくはgituhub上に書いてもらうでもOKです）

よろしくお願いします！

2023-06-27 00:28 UTC, yumi0109 commented on task6/task6.js
> +
@poemypoemy8 
コメントありがとうございます！

テーブルの構造、もう一度資料を参考にして、見てみます。
基本的なところが理解できていないまま、なんとなくできたというものもあるため、他の書き方での書き方になると急に分からなっている状況で、お手数お掛けしてしまってすみません...。

今やっている課題にひと段落ついたら、.shift メソッドのことと、それを利用しない方法での書き方模索してみます。
修正が出来上がり次第またプルリクエストを送らせていただきますので、よろしくお願いします。

2023-06-27 03:20 UTC, yumi0109 commented
@poemypoemy8 
お疲れさまです！
教えていただいたkintoneのテーブルの記事から、テーブルの書き方を変更しました。
ご確認をよろしくお願いいたします。

(.shiftの動きについても自分で理解したいと思ったのですが、ひとまずテーブルの記述を変更したものでプルリクエストを送らせていただきました🙏🏻)

2023-06-27 05:27 UTC, yumi0109 commented
お疲れさまです！
テーブルの構造を送っていただいたkintone developer networkの資料を参照して変更しました。

『task6 version3』になります。
お手隙の際にご確認よろしくお願いします。

2023-06-28 00:57 UTC, poemypoemy8 approved these changes
修正お疲れさまでした。ばっちりです！！！🙌🙌🙌

2023-06-28 01:01 UTC, poemypoemy8 commented
@yumi0109 
課題お疲れさまでした！

回答とちがうコードの記述方法でも、やり方はひとつじゃないし
色々と調べたことが伝わっていいなと思ったのですが、
今回は「記述の内容を理解する」という部分が大事かと思い、
やいやい言ってしまいましたm(_ _)m

大きく修正するの気持ち的に大変だったと思いますが、
見直して修正してくださってありがとうございました🙏

マージしてもらって大丈夫です！

2023-06-28 08:02 UTC, merged

2023-06-28 08:05 UTC, yumi0109 commented
@poemypoemy8 
レビューありがとうございます。

基本的な知識も十分でなく、いろいろなやり方を模索することは今の自分位とっては簡単ではありませんが、いろいろなやり方を試した方が勉強になるので、ありがたいです🙏🏻

見ずらい書き方でお手数お掛けしていると思いますが、製品研修等の課題でも何でも言っていただけると嬉しいです！

何度もご確認とコメントやヒントありがとうございました！