Task5
yumi0109/kintone_dojo pull request #7
Opened 2023-06-26 07:27 UTC by yumi0109

中間課題を提出させていただきます。

21行目の『query: 'order by day desc limit 5'』で表示できるニュース記事の最大表示数を3に制限することの問題に関して記述したものですが、『満たすべき条件』と『余裕があれば』の問題を同じファイルに記述しているため、limit3ではなく、llimit5で記述しました。

お手隙の際にご確認よろしくお願いいたします。

2023-06-28 00:33 UTC, poemypoemy8 requested changes

2023-06-28 00:33 UTC, poemypoemy8 commented on task5/midterm_task.html
> +      td2.innerHTML = `<a class = "${resp.data[key].label.value}"> ${resp.data[key].category.value} </a>`;
ここで<a>タグを追加している影響で、
背景色がaタグの範囲だけについているように見えました。

すでに insertCellでtdタグが付与されている状態だと思うので、
クラス名を書き換えるなど、 
色の指定をする方法をもう少し探ってみてください！

あとはChromeなどの「検証」モードをつかって、記載したコードが
どの要素につながっているか確認しながら書いてみると
わかりやすいと思いました！

2023-06-28 00:48 UTC, poemypoemy8 commented
@yumi0109 
お疲れさまです！
とても見やすく、整理されたコードだと思いました！！👏

あともう少しだけ、以下がんばってください！
上記で記載した背景色の指定について、CSSをどのようにしてあてるか、
（HTMLの書き換えなど）検討してみてください。

2023-07-03 01:16 UTC, yumi0109 commented
@poemypoemy8 
お疲れさまです！
カテゴリーの色分けのCSSを設定し直しました。
htmlファイルの方に、swich文でidを指定しました。

ご確認よろしくお願いします！

2023-07-03 05:47 UTC, poemypoemy8 requested changes

2023-07-03 05:47 UTC, poemypoemy8 commented on task5/midterm_task.html
> +      };
switch文を使っていて条件分けが出来ていて、いい感じです！
こちらで `id`を付与していますが、
idはある特定の1箇所にのみ適用させるものです！
（つまり、2つおなじ名前のidは一般的には存在させません）
参考：https://amsstudio.jp/content/id-attribute-class-attribute

複数の場所に同様のCSSをきかせたいときは、
`class`で指定してあげてください🙏

2023-07-03 05:48 UTC, poemypoemy8 commented
@yumi0109 
おつかれさまです！
背景色を付ける部分、ばっちり修正されていていい感じでした🙌

あともう少し！！！
あらためて「id」と「class」の使い分けの部分を確認お願いします！

2023-07-04 08:00 UTC, yumi0109 commented
@poemypoemy8 
idとしたことをclassに変更しました。
ご確認よろしくお願いします！

2023-07-06 12:41 UTC, poemypoemy8 approved these changes
OKです！！！
マージいただいて大丈夫です。長らくお疲れさまでしたヽ(^。^)ノ

2023-07-07 00:32 UTC, merged