Task7
yumi0109/kintone_dojo pull request #8
Opened 2023-06-27 05:39 UTC by yumi0109

いつもレビューありがとうございます。

『kintone JavaScript API ②』のtask7の提出になります。

お手隙の際にご確認よろしくお願いいたします。

2023-06-28 01:30 UTC, poemypoemy8 requested changes

2023-06-28 01:30 UTC, poemypoemy8 commented on task7/task7.js
> +    if (productName === 'kintone') {
ifでの記述でも問題ないのですが、
せっかくなのでswitch 文での記載 にしてみましょう！

2023-06-28 01:30 UTC, poemypoemy8 commented on task7/task7.js
> +  kintone.events.on(['app.record.create.show', 'app.record.edit.show', field], (event) => {
`重複禁止項目_文字列`の「編集を不可にするタイミング」と
`event.record.サイボウズ製品.value`のフィールドごとに
値を変更させる処理は明確には別だと思うので、
イベントを分けて記述しましょう！

`kintone.events.on` を2回記述して、
それぞれにあった処理内容を記載するイメージです

2023-06-28 01:31 UTC, poemypoemy8 commented
@yumi0109 
課題お疲れさまです！
おおむねOKなので、後はレビューしたところの記述を考え直してみてください

もう少しだけ頑張ってください！ よろしくお願いします🙏

2023-07-04 08:06 UTC, yumi0109 commented
@poemypoemy8 
task7を修正して、再提出させていただきました。
お手隙の際に、ご確認お願いします！

2023-07-06 12:48 UTC, poemypoemy8 requested changes

2023-07-06 12:48 UTC, poemypoemy8 commented on task7/task7.js
> +  'use strict';
```
  kintone.events.on([
    'app.record.create.show',
    'app.record.edit.show'
  ],(event) => {
    event.record.重複禁止項目_文字列.disabled = true;
    return event;
  });
```

`event.record.重複禁止項目_文字列.disabled = true;` の処理(重複禁止項目を編集不可にする)は、
create/edit のイベントが起こったときだけで大丈夫です！

今のままの記述だと、日付を変えたとき、サイボウズ製品を変えたときなど、
細かくイベントが起こることになり無駄な処理になってしまうと思います。

上記のように、重複禁止項目の編集不可にする処理だけ締め出しだけお願いします！🙏
そこだけ修正いただければマージしてOKです！

2023-07-06 12:49 UTC, poemypoemy8 commented
@yumi0109 
↑だけ修正お願いしますm(_ _)m あともうちょっと…！！！

2023-07-07 01:37 UTC, yumi0109 commented
@poemypoemy8 
ご確認ありがとうございます。

重複禁止をの項目を元々設定してたeventの中から取り出し、create/edit のイベントが起こったときだけにできるよう、38行目以降に記述しました。

お手隙の際にご確認よろしくお願いします。

2023-07-07 05:24 UTC, poemypoemy8 approved these changes

2023-07-07 05:24 UTC, poemypoemy8 commented on task7/task7.js
> +
もうほぼOKなので、これだけ修正してからマージしてください🙏
以下の編集禁止にするコードは、レコード作成・編集時に起こすものだと思います。
Javascriptは上から実行されるので、
上部のフィールド変更時のイベント処理よりも前(上)に来る方が自然だと思います。

```
 kintone.events.on([
    'app.record.create.show',
    'app.record.edit.show'
  ],(event) => {
    event.record.重複禁止項目_文字列.disabled = true;
    return event;
  });
```

ここだけ修正したらマージしてもらってOKです！

2023-07-10 00:31 UTC, merged

2023-07-10 00:33 UTC, yumi0109 commented on task7/task7.js
> +
@poemypoemy8 
ご確認ありがとうございます。

順番を訂正して、マージさせていただきました。
確かに、JavaScriptを書く順番も適切なものにするべきだなと思いました。

レビューありがとうございました！