Task9
yumi0109/kintone_dojo pull request #9
Opened 2023-06-27 06:17 UTC by yumi0109

『kintone REST API ②』の課題の提出です。
task9になります。

お手隙の際にご確認よろしくお願いします。

2023-06-28 04:35 UTC, poemypoemy8 requested changes

2023-06-28 04:35 UTC, poemypoemy8 commented on task9/task9.js
> +    const appId = kintone.app.getId();
`const appId = kintone.app.getId();`

書き方があっているかもう一度確認いただきたいです！

2023-06-28 04:36 UTC, poemypoemy8 commented
@yumi0109 
おつかれさまです！すごい！！！
ほぼOKです。

記載があっているか確認いただきたい点を上記に記載したので、確認して修正おねがいします。

2023-07-04 08:13 UTC, yumi0109 commented
@poemypoemy8 
task9を修正しました。
お手隙の際にご確認よろしくお願いします。

2023-07-06 14:11 UTC, poemypoemy8 requested changes

2023-07-06 14:11 UTC, poemypoemy8 commented on task9/task9.js
> +      query: `重複禁止項目 = "${content}"`,
前回のレビュー時指摘できていなかったのですが、1点確認お願いします。

例えば今のコードだと、
一度レコード新規登録時の内容で、レコード編集画面に遷移し何も変えずに
保存しようとすると、自分のレコードにも重複判定がかかるとおもいます。

重複判定をかける範囲を、
「自分のレコードは判定に含まない」という形にできるように修正お願いします！
具体的には、以下の記事を参考にクエリの書き方を工夫してみてください。
https://cybozu.dev/ja/kintone/docs/overview/query/

ヒント：
` const recordId = kintone.app.record.getId();` としておき、
``重複禁止項目 = "${content}" and なんちゃら` のような形でクエリの絞り込みを記載できないでしょうか？

2023-07-07 01:31 UTC, yumi0109 commented
お疲れさまです！
レビューありがとうございます。

動作を確認したところ、ぽえみーさんのご指摘お通り、自分の登録したレコードの編集画面から内容を変更せずに登録しようとすると、重複とカウントされてしまったため、5-7行目とparamsの中身を修正しました。

お手隙の際に、ご確認よろしくお願いします。

2023-07-07 05:26 UTC, poemypoemy8 approved these changes

2023-07-07 05:28 UTC, poemypoemy8 commented
@yumi0109 
修正お疲れさまでした！
クエリの書き方が修正されていて、レコードIDにより絞り込みを分岐する形になっているのでレビューOKにさせていただきます。

長らくお疲れさまでした！
あともう少し残っている課題も頑張ってください。

どこの部署でも、JSは書けると対応できる幅が広がると思います。
研修が終わったら復習してもらえるとめっちゃいいと思います！ 以上おつかれさまでしたm(_ _)m

2023-07-10 00:34 UTC, merged